### ISSUE TITLE
What's the stability of this crate?

### ISSUE THREAD

**Issue by Kleptine** [mullvad/windows-service-rs#21]
This looks like exactly what I need! How stable / finished is the implementation? Would it be reasonable to depend on it for a simple utility service I'm looking to put together?

**Comment by pronebird** [comment]
We've been using it in [production](https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-daemon/src/system_service.rs) for quite a while now and it works very well. It does require a little bit of boilerplate to get started with, but then you get a lot of flexibility. I am pretty sure you should be able to build a simple windows service using this crate. We have a few missing bits here and there but overall we've implemented a big part of the services API on Windows. We may be introducing some breaking changes to improve ergonomics though.

**Comment by Kleptine** [comment]
Perfect thanks. :) Just as a curiosity, how do you handle services on OSX and Linux? I'm looking to support those platforms as well. Do you have similar crates on those platforms?

**Comment by pronebird** [comment]
It’s simpler on macOS and Linux where services are managed via configuration files. 

Ioctl protocol is used for the IPC between user land and the services, something that Windows services implement via control events, but we don’t really use or expose anything via ioctl since we have our own RPC.

[1] macOS https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/pkg-scripts/postinstall

[2] Linux https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/linux/mullvad-daemon.service and https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/linux/mullvad-daemon.conf
