### ISSUE TITLE
Getting Error on connecting to service controller?

### ISSUE THREAD

**Issue by shirshak55** [mullvad/windows-service-rs#53]
Hmm its quite strange but i see this weird error.

its exactly failing on this line

https://github.com/sgfreshidea/shopee_log_backend/blob/master/src/system_service.rs#L18

```
error=Winapi(Os { code: 1063, kind: Other, message: "The service process could not connect to the service controller." })
```

Its so strange :(

**Comment by faern** [comment]
Is the process running with enough privileges?

**Comment by shirshak55** [comment]
Yes i did run with admin right.

**Comment by pronebird** [comment]
Based on [MSDN docs](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatcherw) it looks like you the following error:

> ERROR_FAILED_SERVICE_CONTROLLER_CONNECT
>This error is returned if the program is being run as a console application rather than as a service.
>If the program will be run as a console application for debugging purposes, structure it such that service-specific code is not called when this error is returned.

That's said I think you are trying to run your service as console program, but the service process has to be started by the system service controller itself. You have to register the binary with the service controller then start it from there.

The example regarding the service installation on Windows is provided here:
https://github.com/mullvad/windows-service-rs/blob/master/examples/install_service.rs

Alternatively you can install the service using `sc.exe` as described here:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create

Then to run you service simply execute `sc start <service_name>`.

There are also articles on the internet that describe how to wrap your program in order to run it as a console program, i.e:

https://makolyte.com/run-a-windows-service-as-a-console-app/

The principle is as simply as passing some flag to binary & run the service as if it was a console program, we don't have any facilities out of box, but it should be possible to execute an alternative code path to run the service as a console program.

**Comment by shirshak55** [comment]
@pronebird hello i actually got the service installed properly but when i run its the issue i guess.

**Comment by pronebird** [comment]
@shirshak55 Hello! 

I always suggest to start with our examples, build `ping_service` then build `install_service` from examples folder. Run `install_service` to install `ping_service`, then try running it as a service. See if those two work, as they have been tested many times & should work.

When registering a service, make sure that you provide the correct path to binary and that the service name matches. What Windows do you run btw?

**Comment by shirshak55** [comment]
@pronebird Ok its not my fault i think.

```
shirshak_cute_boi@DESKTOP-FBU1KQN MSYS ~/Desktop/dev/windows-service-rs (master)
$ cargo run --example ping_service
   Compiling windows-service v0.3.0 (C:\Users\sgfreshidea\Desktop\dev\windows-service-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target\debug\examples\ping_service.exe`
Error: Winapi(Os { code: 1063, kind: Other, message: "The service process could not connect to the service controller." })
error: process didn't exit successfully: `target\debug\examples\ping_service.exe` (exit code: 1)
```

**Comment by pronebird** [comment]
@shirshak55 as I had pointed out, you cannot run the system service as a console app. You have to run it as a service, i.e:

```
sc.exe start ping_service
```

**Comment by shirshak55** [comment]
@pronebird Sorry! I thought sc would have been handled just like windows service :(. May be the example should use std::process::Command so we wont be confused :) 


Thank You so much.

**Comment by pronebird** [comment]
@shirshak55 we left some instructions in [the header comment](https://github.com/mullvad/windows-service-rs/blob/master/examples/ping_service.rs#L3-L13):

> You can install and uninstall this service using other example programs.
> All commands mentioned below shall be executed in Command Prompt with Administrator privileges.
> 
> Service installation: `install_service.exe`
> Service uninstallation: `uninstall_service.exe`
> 
> Start the service: `net start ping_service`
> Stop the service: `net stop ping_service`
> 
> Ping server sends a text message to local UDP port 1234 once a second.
> You can verify that service works by running netcat, i.e: `ncat -ul 1234`.

Maybe we could improve the README to make it more obvious how to run the windows service binary. I thought examples were super easy to follow.
