### ISSUE TITLE
Migrate to `windows`/`-sys` crate

### ISSUE THREAD

**Issue by ok-nick** [mullvad/windows-service-rs#68]
`winapi` is a community-maintained crate for windows bindings that has received only a single update in the last year. Microsoft has officially released their own set of bindings providing both a raw low-level crate, `windows-sys`, and a higherish-level crate (with some helper traits and etc), `windows`.

As the general Rust ecosystem is migrating to the new windows crates, `windows-service` should follow. It would be preferable to use the `windows-sys` crate over the `windows` crate to cut down compile times.

**Comment by faern** [comment]
Hi,

I agree that over time the Rust ecosystem should probably move over to `windows`/`windows-sys`. I know `parking_lot` already has, and `mio` is working on it. But I find it somewhat problematic that `windows-sys` releases so many breaking changes. Since its initial release 5 months ago there has been nine semver incompatible releases. This is fine for an experimental and unstable early library! But I'm a bit hesitant towards moving production ready stuff over to it already.

> to cut down compile times.

If many crates move over and `windows-sys` continues to release breaking changes then suddenly everyone will have 3-4 versions of this crate in their dependency tree. That's not optimal. I don't think it will cut down compile times :see_no_evil: 

For crates that only uses the Windows SDK internally the downside of the breaking changes is only the added compile time/binary bloat of having multiple versions in the dependency tree. But for any crate that exposes Windows SDK types publicly a breaking change in the bindings is a breaking change in the library itself. `windows-service` does expose some `winapi` types publicly (example: https://docs.rs/windows-service/latest/windows_service/service/struct.SessionNotification.html#method.from_raw), so if we were to migrate it would be a breaking change, and any upgrade of `windows-sys` would **also** be a breaking change for `windows-service`. This would create a lot of churn and if a lot of crates do this it will be a pretty large split in the ecosystem.

So I think two things we should do before blindly migrating is:

1. Wait a little longer and see if `windows-sys` stabilizes and how other crates decides to handle it.
2. Check if we can stop having parts of `winapi` in the public API of `windows-service` without losing functionality or ergonomics.

**Comment by yescallop** [comment]
FYI, I have tried the migration in yescallop/windows-service-rs@5c9abd3. Feel free to use that commit if you need it.

**Comment by joseluisq** [comment]
> FYI, I have tried the migration in [yescallop/windows-service-rs@5c9abd3](https://github.com/yescallop/windows-service-rs/commit/5c9abd3). Feel free to use that commit if you need it.

@yescallop I played around with your fork and works like a charm!

So looking forward to see some similar upgrade path for the current project on near future.
